
###
GET http://localhost:8000/api/timeout

#users
###
GET  http://localhost:8000/api/users/1

###
GET  http://localhost:8000/api/users

###
POST  http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "userId":4,
    "password": "pass",
    "username": "Alvin",
    "role": "admin"
}

###

POST  http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "username": "Alvin",
    "password": "pass"
}

###
GET http://localhost:8000/api/users/
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBbHZpbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODAzNzI0M30.GVNxfqa53z_BtpHwjX_ptcLptQ_2qR8dyWBkYZO5L68

###
GET http://localhost:8000/api/users?limit=4

###
GET  http://localhost:8000/api/user/1/orders

###
GET  http://localhost:8000/api/user/1/comments

### 
POST  http://localhost:8000/api/users
Content-Type: application/json

{
    "name": "john",
    "contact_phone": "11111111",
    "phone_verified":false,
    "email": "john@example.com",
    "email_verified": true,
    "confirmation_code": "password123",
    "password": "123"

}

###
PUT  http://localhost:8000/api/users/6
Content-Type: application/json

{
    "name": "johnte njoroge",
    "contact_phone": "11111111",
    "phone_verified":false,
    "email": "john@example.com",
    "email_verified": true,
    "confirmation_code": "password123",
    "password": "123"

}

###
DELETE   http://localhost:8000/api/users/6
Content-Type: application/json

{
    "name": "johnte njoroge",
    "contact_phone": "11111111",
    "phone_verified":false,
    "email": "john@example.com",
    "email_verified": true,
    "confirmation_code": "password123",
    "password": "123"

}

###
GET  http://localhost:8000/api/restaurants/1

###

POST   http://localhost:8000/api/restaurants
Content-Type: application/json


{
  "name": "Krusty Crub",
  "street_address": "Main St",
  "zip_code": "00008",
  "city_id": 4
}
###

PUT    http://localhost:8000/api/restaurants/6
Content-Type: application/json


{
  "name": "Krusty Crub",
  "street_address": "Main St",
  "zip_code": "00008",
  "city_id": 4
}
###

DELETE     http://localhost:8000/api/restaurants/6
Content-Type: application/json


{
  "name": "Krusty Crub",
  "street_address": "Main St",
  "zip_code": "00008",
  "city_id": 4
}

#states
###
GET  http://localhost:8000/api/states/1

###
POST http://localhost:8000/api/states
Content-Type: application/json


{
  "name": "Manhattan",
  "code": "MH"
}

###
PUT   http://localhost:8000/api/states/6
Content-Type: application/json


{
  "name": "State of Manhattan ",
  "code": "MH"
}

###
DELETE   http://localhost:8000/api/states/6
Content-Type: application/json


{
  "name": "State of Manhattan ",
  "code": "MH"
}

# cities
###
GET  http://localhost:8000/api/cities/1



###
POST  http://localhost:8000/api/cities
Content-Type: application/json


{
  "name": "Berlin",
  "state_id": 1
}


###
PUT  http://localhost:8000/api/cities/7
Content-Type: application/json


{
  "name": "Munich",
  "state_id": 4
}


###
DELETE   http://localhost:8000/api/cities/6
Content-Type: application/json


{
  "name": "Munich",
  "state_id": 4
}

# Orders
###
GET  http://localhost:8000/api/orders/1

###
POST   http://localhost:8000/api/orders
Content-Type: application/json

{
  "restaurant_id": 1,
  "estimated_delivery_time": "2024-06-09T12:14:18Z",
  "actual_delivery_time": "2024-06-09T14:14:18Z",
  "delivery_address_id": 1,
  "user_id": 1,
  "driver_id": 1,
  "price": 25.99,
  "discount": 5.00,
  "final_price": 20.99,
  "comment": "Extra ketchup"
}


###
PUT   http://localhost:8000/api/orders/6
Content-Type: application/json

{
  "restaurant_id": 2,
  "estimated_delivery_time": "2024-06-07 18:30:00",
  "actual_delivery_time": "2024-06-06 18:50:00",
  "delivery_address_id": 2,
  "user_id": 2,
  "driver_id": 2,
  "price": 32.99,
  "discount": 0.00,
  "final_price": 32.99,
  "comment": "No onions"
}

###
DELETE    http://localhost:8000/api/orders/6
Content-Type: application/json

{
  "restaurant_id": 2,
  "estimated_delivery_time": "2024-06-07 18:30:00",
  "actual_delivery_time": "2024-06-06 18:50:00",
  "delivery_address_id": 2,
  "user_id": 2,
  "driver_id": 2,
  "price": 32.99,
  "discount": 0.00,
  "final_price": 32.99,
  "comment": "No onions"
}

# Order Menu Items
###
GET  http://localhost:8000/api/order_menu_items/1

###
POST  http://localhost:8000/api/order_menu_items
Content-Type: application/json

{
  "order_id": 1,
  "menu_item_id": 1,
  "quantity": 2,
  "item_price": 10.99,
  "price": 21.98,
  "comment": "Extra spicy"
}

###
PUT  http://localhost:8000/api/order_menu_items/6
Content-Type: application/json

{
  "order_id": 2,
  "menu_item_id": 3,
  "quantity": 1,
  "item_price": 8.99,
  "price": 8.99,
  "comment": "No cheese"
}

###
DELETE  http://localhost:8000/api/order_menu_items/6
Content-Type: application/json

{
  "order_id": 2,
  "menu_item_id": 3,
  "quantity": 1,
  "item_price": 8.99,
  "price": 8.99,
  "comment": "No cheese"
}

# Order Statuses
###
GET  http://localhost:8000/api/order_statuses/1

###
POST  http://localhost:8000/api/order_statuses
Content-Type: application/json

{
  "order_id": 1,
  "status_catalog_id": 1
}

###
PUT  http://localhost:8000/api/order_statuses/6
Content-Type: application/json

{
  "order_id": 2,
  "status_catalog_id": 3
}

###
DELETE  http://localhost:8000/api/order_statuses/6
Content-Type: application/json

{
  "order_id": 2,
  "status_catalog_id": 3
}

# Status Catalogs
###
GET  http://localhost:8000/api/status_catalogs/1

###
POST  http://localhost:8000/api/status_catalogs
Content-Type: application/json

{
  "name": "Delivered"
}

###
PUT  http://localhost:8000/api/status_catalogs/6
Content-Type: application/json

{
  "name": "Cancelled"
}

###
DELETE  http://localhost:8000/api/status_catalogs/6
Content-Type: application/json

{
  "name": "Cancelled"
}

# Comments
###
GET  http://localhost:8000/api/comments/1

###
POST  http://localhost:8000/api/comments
Content-Type: application/json

{
  "user_id": 1,
  "order_id": 1,
  "comment": "Great service",
  "is_complaint": false,
  "is_praise": true
}

###
PUT  http://localhost:8000/api/comments/6
Content-Type: application/json

{
  "user_id": 2,
  "order_id": 2,
  "comment": "Late delivery",
  "is_complaint": true,
  "is_praise": false
}

###
DELETE  http://localhost:8000/api/comments/6
Content-Type: application/json

{
  "user_id": 2,
  "order_id": 2,
  "comment": "Late delivery",
  "is_complaint": true,
  "is_praise": false
}

# Categories
###
GET  http://localhost:8000/api/categories/1

###
POST  http://localhost:8000/api/categories
Content-Type: application/json

{
  "name": "Appetizers"
}

###
PUT  http://localhost:8000/api/categories/6
Content-Type: application/json

{
  "name": "Main Course"
}

###
DELETE  http://localhost:8000/api/categories/6
Content-Type: application/json

{
  "name": "Main Course"
}

# Restaurant Owners
###
GET  http://localhost:8000/api/restaurant_owners/1/1

###
POST  http://localhost:8000/api/restaurant_owners
Content-Type: application/json

{
  "restaurant_id": 1,
  "owner_id": 1
}

###
PUT  http://localhost:8000/api/restaurant_owners/1/1
Content-Type: application/json

{
  "restaurant_id": 1,
  "owner_id": 1
}

###
DELETE  http://localhost:8000/api/restaurant_owners/1/1
Content-Type: application/json

{
  "restaurant_id": 1,
  "owner_id": 1
}

# Addresses
###
GET  http://localhost:8000/api/addresses/1

###
POST  http://localhost:8000/api/addresses
Content-Type: application/json

{
  "street_address_1": "123 Main St",
  "street_address_2": "Apt 4B",
  "zip_code": "10001",
  "delivery_instructions": "Leave at front desk",
  "user_id": 1,
  "city_id": 1
}

###
PUT  http://localhost:8000/api/addresses/6
Content-Type: application/json

{
  "street_address_1": "456 Elm St",
  "street_address_2": "Suite 3A",
  "zip_code": "10002",
  "delivery_instructions": "Ring bell twice",
  "user_id": 2,
  "city_id": 2
}

###
DELETE  http://localhost:8000/api/addresses/6
Content-Type: application/json

{
  "street_address_1": "456 Elm St",
  "street_address_2": "Suite 3A",
  "zip_code": "10002",
  "delivery_instructions": "Ring bell twice",
  "user_id": 2,
  "city_id": 2
}

# Drivers
###
GET  http://localhost:8000/api/drivers/1

###
POST  http://localhost:8000/api/drivers
Content-Type: application/json

{
  "car_make": "Toyota",
  "car_model": "Corolla",
  "car_year": 2020,
  "user_id": 1,
  "online": true,
  "delivering": false
}

###
PUT  http://localhost:8000/api/drivers/6
Content-Type: application/json

{
  "car_make": "Honda",
  "car_model": "Civic",
  "car_year": 2019,
  "user_id": 2,
  "online": false,
  "delivering": true
}

###
DELETE  http://localhost:8000/api/drivers/6
Content-Type: application/json

{
  "car_make": "Honda",
  "car_model": "Civic",
  "car_year": 2019,
  "user_id": 2,
  "online": false,
  "delivering": true
}

# Menu Items
###
GET  http://localhost:8000/api/menu_items/1

###
POST  http://localhost:8000/api/menu_items
Content-Type: application/json

{
  "name": "Burger",
  "restaurant_id": 1,
  "category_id": 1,
  "description": "A delicious burger",
  "ingredients": "Beef, Lettuce, Tomato, Bun",
  "price": 9.99,
  "active": true
}

###
PUT  http://localhost:8000/api/menu_items/6
Content-Type: application/json

{
  "name": "Cheeseburger",
  "restaurant_id": 2,
  "category_id": 2,
  "description": "A delicious cheeseburger",
  "ingredients": "Beef, Cheese, Lettuce, Tomato, Bun",
  "price": 10.99,
  "active": true
}

###
DELETE  http://localhost:8000/api/menu_items/6
Content-Type: application/json

{
  "name": "Cheeseburger",
  "restaurant_id": 2,
  "category_id": 2,
  "description": "A delicious cheeseburger",
  "ingredients": "Beef, Cheese, Lettuce, Tomato, Bun",
  "price": 10.99,
  "active": true
}